# Generated by Django 3.1.7 on 2021-04-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bookname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
